# Generated by Django 5.1.3 on 2025-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_userprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
