# Generated by Django 5.1.3 on 2025-09-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_weeklyscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='school',
        ),
    ]
